# -*- coding: utf-8 -*-
"""
Semilla oficial con los 46 equipos reales levantados en Manufacturas Olamtex.
Incluye nombres de colaboradores, hostnames, IPs fijas, cargos y dependencias de red.
"""

EQUIPOS_OLAMTEX = [
  # SÓTANO (1 EQUIPO)
  {
    "id": "laptop-sotano",
    "nombre": "Portátil Sótano (Almacén)",
    "piso": "Sótano",
    "tipo": "Laptop / Portátil",
    "ip": "192.168.0.140",
    "mac": "C8:3A:35:71:00:22",
    "hostname": "LAPTOP-SOTANO-BOD",
    "usuario": "Operario Almacén / Telas",
    "cargo": "Recepción y Despacho Telas",
    "so": "Windows 11 Home 64-bit",
    "hardware": "Core i5 / 8GB RAM / 512GB SSD",
    "marca": "Lenovo ThinkPad",
    "conectado_id": "modem-corte",
    "conectado": "Módem de Corte (Piso 1)",
    "enlace_tipo": "Wi-Fi (Inalámbrico)",
    "puerto_switch": "SSID Corte (Cobertura hacia Sótano)",
    "software": "Navegador Web, Software Inventarios",
    "alerta": "Normal",
    "notas": "Portátil utilizado en el sótano para conteo de telas. Conectado vía Wi-Fi al módem de corte."
  },

  # PISO 1 (PLANTAS, CORTE Y BODEGAS - 5 EQUIPOS)
  {
    "id": "modem-corte",
    "nombre": "Módem de Corte (Piso 1)",
    "piso": "Piso 1",
    "tipo": "Router / Gateway",
    "ip": "192.168.0.10",
    "mac": "E4:8D:8C:33:44:01",
    "hostname": "MODEM-CORTE-P1",
    "usuario": "Operarios de Corte",
    "cargo": "Conectividad Planta y Enlace Sótano",
    "so": "Firmware Módem Proveedor",
    "hardware": "Router Wi-Fi Dual Band Gigabit",
    "marca": "Módem ISP",
    "conectado_id": "sw-hp",
    "conectado": "Switch Core HP 24p",
    "enlace_tipo": "Cable UTP Cat 6",
    "puerto_switch": "Puerto Directo a Switch HP Core",
    "software": "Wi-Fi Corte 2.4/5GHz",
    "alerta": "Normal",
    "notas": "Módem de área de corte conectado directamente por cable al Switch Core HP. Brinda señal Wi-Fi a corte, bodega y sótano."
  },
  {
    "id": "ap-corte",
    "nombre": "AP Corte",
    "piso": "Piso 1",
    "tipo": "Wi-Fi / AP",
    "ip": "192.168.0.18",
    "mac": "E4:8D:8C:33:44:02",
    "hostname": "AP-CORTE-P1",
    "usuario": "Operarios de Corte",
    "cargo": "Cobertura Wi-Fi Área Corte",
    "so": "Firmware AP",
    "hardware": "Access Point Wi-Fi N/AC",
    "marca": "Comercial",
    "conectado_id": "modem-corte",
    "conectado": "Módem de Corte (Piso 1)",
    "enlace_tipo": "Cable UTP Cat 6",
    "puerto_switch": "LAN Módem Corte",
    "software": "Wi-Fi Corte",
    "alerta": "Normal",
    "notas": "Punto de acceso para cobertura en taller de confección y corte."
  },
  {
    "id": "pc-bodega-1",
    "nombre": "Bodega Uno",
    "piso": "Piso 1",
    "tipo": "Puesto de Trabajo",
    "ip": "192.168.1.240",
    "mac": "B4:2E:99:40:11:01",
    "hostname": "AUXBOD1",
    "usuario": "CIFUENTES POSADA JUAN MANUEL",
    "cargo": "AUXILIAR LOGISTICO",
    "so": "Windows 10 Pro 64-bit",
    "hardware": "Core i3 / 8GB RAM / 256GB SSD",
    "marca": "PC de Mesa",
    "conectado_id": "sw-prod-diseno",
    "conectado": "Switch Producción & Diseño",
    "enlace_tipo": "Cable UTP Cat 6",
    "puerto_switch": "Puesto Bodega 1",
    "software": "Office, ERP Inventario",
    "alerta": "Normal",
    "notas": "Equipo de escritorio Bodega 1 operado por Juan Manuel Cifuentes."
  },
  {
    "id": "pc-bodega-2",
    "nombre": "Bodega Dos",
    "piso": "Piso 1",
    "tipo": "Puesto de Trabajo",
    "ip": "192.168.1.157",
    "mac": "B4:2E:99:40:11:02",
    "hostname": "AUXBOD2",
    "usuario": "CIFUENTES POSADA JUAN MANUEL",
    "cargo": "AUXILIAR LOGISTICO",
    "so": "Windows 10 Pro 64-bit",
    "hardware": "Core i3 / 8GB RAM / 256GB SSD",
    "marca": "PC de Mesa",
    "conectado_id": "modem-corte",
    "conectado": "Módem de Corte (Piso 1)",
    "enlace_tipo": "Wi-Fi (Inalámbrico)",
    "puerto_switch": "SSID Corte",
    "software": "Office, ERP Inventario",
    "alerta": "Normal",
    "notas": "Equipo de escritorio Bodega 2 operado por Juan Manuel Cifuentes."
  },
  {
    "id": "pc-tejeduria",
    "nombre": "PC TEJEDURIA",
    "piso": "Piso 1",
    "tipo": "Puesto de Trabajo",
    "ip": "DHCP",
    "mac": "B4:2E:99:40:11:05",
    "hostname": "PC-TEJEDURIA",
    "usuario": "HERNANDEZ FRANCO DAIRO",
    "cargo": "OPERARIO TEJEDURIA",
    "so": "Windows 10 Pro",
    "hardware": "Core i3 / 8GB RAM / 240GB SSD",
    "marca": "PC de Mesa",
    "conectado_id": "sw-hp",
    "conectado": "Switch Core HP 24p",
    "enlace_tipo": "Cable UTP Cat 6",
    "puerto_switch": "Puesto Tejeduría",
    "software": "Control de Producción / Máquinas",
    "alerta": "Normal",
    "notas": "Puesto de control en área de tejeduría operado por Dairo Hernandez."
  },

  # PISO 2 (CORE MDF, PRODUCCIÓN, DISEÑO, GH, LOGÍSTICA - 28 EQUIPOS)
  {
    "id": "isp-claro",
    "nombre": "Módem ISP 1 (Claro)",
    "piso": "Piso 2",
    "tipo": "Router / Gateway",
    "ip": "IP Pública Dinámica/Fija",
    "mac": "F8:8E:85:12:34:01",
    "hostname": "MODEM-CLARO-WAN1",
    "usuario": "Proveedor Claro",
    "cargo": "Enlace Principal de Internet",
    "so": "Firmware Claro",
    "hardware": "Módem Fibra Óptica",
    "marca": "Claro Colombia",
    "conectado_id": "gw-ruijie",
    "conectado": "Gateway Multi-WAN Ruijie",
    "enlace_tipo": "Fibra Óptica / Coaxial",
    "puerto_switch": "WAN 1 Gateway Ruijie",
    "software": "Bridge Mode",
    "alerta": "Normal",
    "notas": "Enlace principal de fibra óptica Claro."
  },
  {
    "id": "isp-ruijie",
    "nombre": "Módem ISP 2 (Secundario)",
    "piso": "Piso 2",
    "tipo": "Router / Gateway",
    "ip": "IP Pública Dinámica/Fija",
    "mac": "F8:8E:85:12:34:02",
    "hostname": "MODEM-ISP2-WAN2",
    "usuario": "Proveedor Etelco",
    "cargo": "Enlace Respaldo / Failover",
    "so": "Firmware ISP",
    "hardware": "Módem Coaxial/Fibra",
    "marca": "Etelco",
    "conectado_id": "gw-ruijie",
    "conectado": "Gateway Multi-WAN",
    "enlace_tipo": "Cable Ethernet WAN",
    "puerto_switch": "WAN 2 Gateway Ruijie",
    "software": "Failover automático",
    "alerta": "Normal",
    "notas": "Línea secundaria de contingencia provista por Etelco."
  },
  {
    "id": "gw-ruijie",
    "nombre": "Gateway Multi-WAN",
    "piso": "Piso 2",
    "tipo": "Router / Gateway",
    "ip": "192.168.0.1",
    "mac": "E4:A7:C5:99:88:77",
    "hostname": "GW-RUIJIE-MDF",
    "usuario": "Infraestructura TI",
    "cargo": "Borde de Red / Seguridad",
    "so": "Ruijie OS",
    "hardware": "Router Gateway Balanceador Multi-WAN",
    "marca": "Ruijie Reyee",
    "conectado_id": "sw-hp",
    "conectado": "Switch Core HP 24p",
    "enlace_tipo": "Cable UTP Cat 6",
    "puerto_switch": "LAN1 -> Switch HP Puerto 1",
    "software": "Ruijie Cloud, Multi-WAN Balancing, DHCP Server",
    "alerta": "Normal",
    "notas": "Gateway principal y router central en Rack Piso 2."
  },
  {
    "id": "sw-hp",
    "nombre": "Switch Core HP 24p",
    "piso": "Piso 2",
    "tipo": "Switch",
    "ip": "192.168.0.2",
    "mac": "70:10:5C:88:00:1A",
    "hostname": "SW-HP-CORE-P2",
    "usuario": "Infraestructura TI",
    "cargo": "Conmutador Central Empresa",
    "so": "HP ProCurve OS",
    "hardware": "24 Puertos Gigabit 10/100/1000",
    "marca": "HP 24 Puertos",
    "conectado_id": "gw-ruijie",
    "conectado": "Gateway Multi-WAN",
    "enlace_tipo": "Cableado Vertical",
    "puerto_switch": "Troncales hacia todos los switches",
    "software": "VLAN 802.1Q, Spanning Tree",
    "alerta": "Normal",
    "notas": "Switch administrable central en Piso 2. Conecta MDF y troncales a todos los pisos."
  },
  {
    "id": "ups-p2",
    "nombre": "UPS de Rack Piso 2",
    "piso": "Piso 2",
    "tipo": "Energía / UPS",
    "ip": "N/A",
    "mac": "N/A",
    "hostname": "UPS-RACK-P2",
    "usuario": "Gabinete Comunicaciones",
    "cargo": "Protección Eléctrica MDF",
    "so": "Hardware Eléctrico",
    "hardware": "UPS 1500VA para Rack",
    "marca": "Comercial",
    "conectado_id": "sw-hp",
    "conectado": "Switch Core HP 24p",
    "enlace_tipo": "Cableado Eléctrico de Respaldo",
    "puerto_switch": "Alimentación PDU Rack",
    "software": "Gestión de Batería",
    "alerta": "Crítico",
    "notas": "ALERTA CRÍTICA: Batería degradada/agotada. Ante corte de luz, el rack principal se apaga instantáneamente."
  },
  {
    "id": "dvr-cctv",
    "nombre": "DVR Cámaras CCTV",
    "piso": "Piso 2",
    "tipo": "Seguridad / CCTV",
    "ip": "192.168.0.200",
    "mac": "44:19:B6:55:44:33",
    "hostname": "DVR-CCTV-P2",
    "usuario": "Seguridad / Administración",
    "cargo": "Circuito Cerrado de TV (16 Ch)",
    "so": "Linux Embedded DVR",
    "hardware": "Grabador Digital 16 Canales + 4TB HDD",
    "marca": "Hikvision / Dahua",
    "conectado_id": "sw-hp",
    "conectado": "Switch Core HP 24p",
    "enlace_tipo": "Cable UTP Cat 6",
    "puerto_switch": "Puerto 23 Switch Core",
    "software": "Monitoreo Remoto, Grabación 24/7",
    "alerta": "Atención",
    "notas": "Sistema central de cámaras de seguridad."
  },
  {
    "id": "sw-prod-diseno",
    "nombre": "Switch Producción & Diseño",
    "piso": "Piso 2",
    "tipo": "Switch",
    "ip": "192.168.0.5",
    "mac": "C0:25:E9:11:22:33",
    "hostname": "SW-PROD-DISENO-P2",
    "usuario": "Producción y Diseño",
    "cargo": "Conmutador Área Producción",
    "so": "Firmware Switch",
    "hardware": "Switch 16/24 Puertos Gigabit",
    "marca": "Switch de Área",
    "conectado_id": "sw-hp",
    "conectado": "Switch Core HP 24p",
    "enlace_tipo": "Cable UTP Cat 6",
    "puerto_switch": "Uplink a Switch HP Puerto 3",
    "software": "Auto MDI/MDIX",
    "alerta": "Normal",
    "notas": "Switch departamental en Piso 2 para Producción, Diseño, Trazo y Plotter."
  },
  {
    "id": "laptop-prod-01",
    "nombre": "Portátil Producción 01",
    "piso": "Piso 2",
    "tipo": "Laptop / Portátil",
    "ip": "192.168.1.247",
    "mac": "E4:54:E8:22:01:01",
    "hostname": "COODPCC2",
    "usuario": "PARRA GALVIS ADRIANA",
    "cargo": "COORDINADOR DE PRODUCCIÓN",
    "so": "Windows 11 Pro 64-bit",
    "hardware": "Core i5 / 16GB RAM / 512GB SSD",
    "marca": "HP ProBook",
    "conectado_id": "sw-prod-diseno",
    "conectado": "Switch Producción & Diseño",
    "enlace_tipo": "Cable UTP Cat 6",
    "puerto_switch": "Puesto Producción 1",
    "software": "Excel, ERP Producción",
    "alerta": "Normal",
    "notas": "Puesto de producción operado por Adriana Parra."
  },
  {
    "id": "laptop-prod-02",
    "nombre": "Portátil Producción 02",
    "piso": "Piso 2",
    "tipo": "Laptop / Portátil",
    "ip": "192.168.1.179",
    "mac": "E4:54:E8:22:01:02",
    "hostname": "COODPCC1",
    "usuario": "PALACIO HERRERA CARLOS",
    "cargo": "COORDINADOR DE PRODUCCIÓN",
    "so": "Windows 11 Pro 64-bit",
    "hardware": "Core i5 / 16GB RAM / 512GB SSD",
    "marca": "HP ProBook",
    "conectado_id": "sw-prod-diseno",
    "conectado": "Switch Producción & Diseño",
    "enlace_tipo": "Cable UTP Cat 6",
    "puerto_switch": "Puesto Producción 2",
    "software": "Excel, ERP Producción",
    "alerta": "Normal",
    "notas": "Puesto de producción operado por Carlos Palacio."
  },
  {
    "id": "laptop-prod-03",
    "nombre": "Portátil Producción 03",
    "piso": "Piso 2",
    "tipo": "Laptop / Portátil",
    "ip": "192.168.1.173",
    "mac": "E4:54:E8:22:01:03",
    "hostname": "ANALISTACAL",
    "usuario": "TEJADA PEREZ PAULINA",
    "cargo": "ANALISTA JUNIOR CALIDAD Y CONFECCION",
    "so": "Windows 11 Pro 64-bit",
    "hardware": "Core i5 / 8GB RAM / 256GB SSD",
    "marca": "Lenovo IdeaPad",
    "conectado_id": "sw-prod-diseno",
    "conectado": "Switch Producción & Diseño",
    "enlace_tipo": "Cable UTP Cat 6",
    "puerto_switch": "Puesto Producción 3",
    "software": "Office, Gestión Calidad",
    "alerta": "Normal",
    "notas": "Puesto de calidad operado por Paulina Tejada."
  },
  {
    "id": "pc-analista-mt",
    "nombre": "PC ANALISTA M&T",
    "piso": "Piso 2",
    "tipo": "Puesto de Trabajo",
    "ip": "192.168.1.191",
    "mac": "B4:2E:99:40:22:15",
    "hostname": "ANALISTAM&T",
    "usuario": "VELEZ JIMENEZ JUAN CAMILO",
    "cargo": "ANALISTA JUNIOR METODOS, TIEMPO, CALIDAD",
    "so": "Windows 11 Pro",
    "hardware": "Core i5 / 16GB RAM / 512GB SSD",
    "marca": "PC de Mesa",
    "conectado_id": "sw-prod-diseno",
    "conectado": "Switch Producción & Diseño",
    "enlace_tipo": "Cable UTP Cat 6",
    "puerto_switch": "Puesto M&T",
    "software": "Software Análisis Tiempos, Office",
    "alerta": "Normal",
    "notas": "Puesto analista de métodos y tiempos operado por Juan Camilo Vélez."
  },
  {
    "id": "laptop-aux-supervision",
    "nombre": "PORTATIL AUX SUPERVISIÓN",
    "piso": "Piso 2",
    "tipo": "Laptop / Portátil",
    "ip": "192.168.1.194",
    "mac": "E4:54:E8:22:01:20",
    "hostname": "AUXSUPER",
    "usuario": "NO APLICA",
    "cargo": "SUPERVISOR DE PLANTA",
    "so": "Windows 11 Pro",
    "hardware": "Core i5 / 8GB RAM / 256GB SSD",
    "marca": "Laptop Lenovo",
    "conectado_id": "sw-hp",
    "conectado": "Switch Core HP 24p",
    "enlace_tipo": "Cable UTP Cat 6",
    "puerto_switch": "Puerto Switch HP",
    "software": "Control Planta, ERP",
    "alerta": "Normal",
    "notas": "Portátil auxiliar para supervisión de planta."
  },
  {
    "id": "printer-epson-diseno",
    "nombre": "IMPRESORA EPSON DISEÑO",
    "piso": "Piso 2",
    "tipo": "Periférico / Impresora",
    "ip": "192.168.1.206",
    "mac": "00:26:AB:78:90:12",
    "hostname": "IMPRESORAL5590",
    "usuario": "VELEZ FLOREZ VALENTINA",
    "cargo": "DISEÑO",
    "so": "Firmware Impresora",
    "hardware": "Epson EcoTank L5590 Multifuncional",
    "marca": "Epson",
    "conectado_id": "isp-ruijie",
    "conectado": "Módem ISP 2 (Secundario)",
    "enlace_tipo": "Wi-Fi (Inalámbrico)",
    "puerto_switch": "Red Wi-Fi Piso 2",
    "software": "Driver Epson",
    "alerta": "Normal",
    "notas": "Impresora a color asignada a diseño."
  },
  {
    "id": "pc-diseno-01",
    "nombre": "PC Diseño 01",
    "piso": "Piso 2",
    "tipo": "Puesto de Trabajo",
    "ip": "192.168.0.121",
    "mac": "D8:BB:C1:33:02:01",
    "hostname": "COODID",
    "usuario": "VELEZ FLOREZ VALENTINA",
    "cargo": "COORDINADORA INVESTIGACIÓN Y DESARROLLO DE PRODUCTO",
    "so": "Windows 11 Pro 64-bit",
    "hardware": "Core i7 / 32GB RAM / 1TB SSD NVMe",
    "marca": "Estación de Trabajo",
    "conectado_id": "sw-prod-diseno",
    "conectado": "Switch Producción & Diseño",
    "enlace_tipo": "Cable UTP Cat 6",
    "puerto_switch": "Puesto I&D Diseño 1",
    "software": "Adobe Illustrator, Photoshop, Audaces",
    "alerta": "Normal",
    "notas": "Equipo de diseño de alto rendimiento operado por Valentina Vélez."
  },
  {
    "id": "pc-diseno-02",
    "nombre": "PC Diseño 02",
    "piso": "Piso 2",
    "tipo": "Puesto de Trabajo",
    "ip": "192.168.1.202",
    "mac": "D8:BB:C1:33:02:02",
    "hostname": "ANALISTADIS1",
    "usuario": "CORREA RESTREPO LEIDY JHOANA",
    "cargo": "APRENDIZ SENA ETAPA PRODUCTIVA",
    "so": "Windows 11 Pro 64-bit",
    "hardware": "Core i5 / 16GB RAM / 512GB SSD",
    "marca": "PC de Mesa",
    "conectado_id": "sw-prod-diseno",
    "conectado": "Switch Producción & Diseño",
    "enlace_tipo": "Cable UTP Cat 6",
    "puerto_switch": "Puesto Diseño 2",
    "software": "Adobe Suite, CorelDRAW",
    "alerta": "Normal",
    "notas": "Puesto de diseño operado por Leidy Jhoana Correa."
  },
  {
    "id": "pc-diseno-03",
    "nombre": "PC Diseño 03",
    "piso": "Piso 2",
    "tipo": "Puesto de Trabajo",
    "ip": "192.168.0.123",
    "mac": "D8:BB:C1:33:02:03",
    "hostname": "ANALISTADIS2",
    "usuario": "PEREZ CIFUENTES MARIA ALEJANDRA",
    "cargo": "AUXILIAR DE DISEÑO",
    "so": "Windows 11 Pro 64-bit",
    "hardware": "Core i5 / 16GB RAM / 512GB SSD",
    "marca": "PC de Mesa",
    "conectado_id": "sw-prod-diseno",
    "conectado": "Switch Producción & Diseño",
    "enlace_tipo": "Cable UTP Cat 6",
    "puerto_switch": "Puesto Diseño 3",
    "software": "Adobe Suite, CorelDRAW",
    "alerta": "Normal",
    "notas": "Puesto de diseño operado por María Alejandra Pérez."
  },
  {
    "id": "pc-diseno-04",
    "nombre": "PC Diseño 04",
    "piso": "Piso 2",
    "tipo": "Puesto de Trabajo",
    "ip": "192.168.1.192",
    "mac": "D8:BB:C1:33:02:04",
    "hostname": "ANALISTADIS3",
    "usuario": "OSORIO MANSO YICETH CAMILA",
    "cargo": "APRENDIZ SENA ETAPA PRODUCTIVA",
    "so": "Windows 11 Pro 64-bit",
    "hardware": "Core i5 / 16GB RAM / 512GB SSD",
    "marca": "PC de Mesa",
    "conectado_id": "sw-prod-diseno",
    "conectado": "Switch Producción & Diseño",
    "enlace_tipo": "Cable UTP Cat 6",
    "puerto_switch": "Puesto Diseño 4",
    "software": "Adobe Suite, Patrones",
    "alerta": "Normal",
    "notas": "Puesto de diseño operado por Yiceth Camila Osorio."
  },
  {
    "id": "pc-trazo",
    "nombre": "PC Trazo",
    "piso": "Piso 2",
    "tipo": "Puesto de Trabajo",
    "ip": "192.168.1.156",
    "mac": "D8:BB:C1:33:02:05",
    "hostname": "ANALISTADIS4",
    "usuario": "GAVIRIA CASTAÑO SOPHIA",
    "cargo": "ANALISTA JUNIOR DISEÑO CREATIVO",
    "so": "Windows 10 Pro 64-bit",
    "hardware": "Core i7 / 16GB RAM / 512GB SSD + 2da NIC Ethernet",
    "marca": "Estación de Trabajo Trazo",
    "conectado_id": "sw-prod-diseno",
    "conectado": "Switch Producción & Diseño",
    "enlace_tipo": "Cable UTP Cat 6",
    "puerto_switch": "Puesto Trazo",
    "software": "Optitex, Audaces, Driver Plotter",
    "alerta": "Normal",
    "notas": "Equipo dedicado a trazo y patronaje operado por Sophia Gaviria. Conectado cable a cable directamente con el Plotter."
  },
  {
    "id": "plotter",
    "nombre": "Plotter de Corte y Trazos",
    "piso": "Piso 2",
    "tipo": "Periférico / Impresora",
    "ip": "192.168.1.198",
    "mac": "00:1E:C9:44:88:99",
    "hostname": "PLOTTER-CORTE",
    "usuario": "Operario de Trazo",
    "cargo": "Plotter Gran Formato 1.80m",
    "so": "Firmware Plotter Industrial",
    "hardware": "Plotter Textil Gran Formato",
    "marca": "Plotter Textil",
    "conectado_id": "pc-trazo",
    "conectado": "Switch Producción & Diseño",
    "enlace_tipo": "Cable Directo PC-Plotter",
    "puerto_switch": "Conexión Directa NIC2 PC Trazo",
    "software": "Control de Impresión Textil",
    "alerta": "Normal",
    "notas": "Plotter de corte conectado cable a cable directamente al PC Trazo sin pasar por switches intermedios."
  },
  {
    "id": "sw-gh",
    "nombre": "Switch Gestión Humana",
    "piso": "Piso 2",
    "tipo": "Switch",
    "ip": "192.168.0.6",
    "mac": "C0:25:E9:55:66:77",
    "hostname": "SW-GESTION-HUMANA-P2",
    "usuario": "Gestión Humana",
    "cargo": "Conmutador Área GH",
    "so": "Firmware Switch",
    "hardware": "Switch 8 Puertos Gigabit",
    "marca": "Switch Pequeño GH",
    "conectado_id": "sw-hp",
    "conectado": "Switch Core HP 24p",
    "enlace_tipo": "Cable UTP Cat 6",
    "puerto_switch": "Uplink a Switch HP Puerto 5",
    "software": "Plug & Play",
    "alerta": "Normal",
    "notas": "Switch pequeño exclusivo para el área de Gestión Humana."
  },
  {
    "id": "pc-gh-01",
    "nombre": "Puesto GH 01 (Laura Cardona)",
    "piso": "Piso 2",
    "tipo": "Puesto de Trabajo",
    "ip": "192.168.1.165",
    "mac": "3C:D9:2B:11:03:01",
    "hostname": "LIDERTH",
    "usuario": "CARDONA OSORIO LAURA",
    "cargo": "LIDER C&DH",
    "so": "Windows 11 Pro 64-bit",
    "hardware": "Core i5 / 16GB RAM / 512GB SSD",
    "marca": "PC de Mesa",
    "conectado_id": "sw-hp",
    "conectado": "Switch Core HP 24p",
    "enlace_tipo": "Cable UTP Cat 6",
    "puerto_switch": "Puesto GH 1",
    "software": "Nómina, Office, ERP GH",
    "alerta": "Normal",
    "notas": "Puesto de Laura Cardona en Gestión Humana."
  },
  {
    "id": "pc-gh-02",
    "nombre": "Puesto GH 02 (Cristian Giraldo)",
    "piso": "Piso 2",
    "tipo": "Puesto de Trabajo",
    "ip": "192.168.1.161",
    "mac": "3C:D9:2B:11:03:02",
    "hostname": "ANALISTASST",
    "usuario": "SANCHEZ ORTEGA KAREN NAYITH",
    "cargo": "ANALISTA DE SEGURIDAD Y SALUD EN EL TRABAJO",
    "so": "Windows 11 Pro 64-bit",
    "hardware": "Core i5 / 16GB RAM / 512GB SSD",
    "marca": "PC de Mesa",
    "conectado_id": "sw-gh",
    "conectado": "Switch Gestión Humana",
    "enlace_tipo": "Cable UTP Cat 6",
    "puerto_switch": "Puesto GH 2",
    "software": "Office, SST, Gestión",
    "alerta": "Normal",
    "notas": "Puesto de SST operado por Karen Nayith Sánchez."
  },
  {
    "id": "pc-gh-03",
    "nombre": "Puesto GH 03 (Auxiliar)",
    "piso": "Piso 2",
    "tipo": "Puesto de Trabajo",
    "ip": "192.168.1.164",
    "mac": "3C:D9:2B:11:03:03",
    "hostname": "ANALISTAADMIN",
    "usuario": "ZAPATA AGUIRRE MARIA ALEJANDRA",
    "cargo": "ANALISTA ADMINISTRATIVA",
    "so": "Windows 11 Pro 64-bit",
    "hardware": "Core i3 / 8GB RAM / 256GB SSD",
    "marca": "PC de Mesa",
    "conectado_id": "sw-gh",
    "conectado": "Switch Gestión Humana",
    "enlace_tipo": "Cable UTP Cat 6",
    "puerto_switch": "Puesto GH 3",
    "software": "Office, Archivo, Contratos",
    "alerta": "Normal",
    "notas": "Puesto auxiliar GH operado por María Alejandra Zapata."
  },
  {
    "id": "pc-logistica",
    "nombre": "PC Logistica (Mesa)",
    "piso": "Piso 2",
    "tipo": "Puesto de Trabajo",
    "ip": "192.168.1.163",
    "mac": "B4:2E:99:40:02:01",
    "hostname": "COODLOG",
    "usuario": "TORO GARCIA JUAN JOSE",
    "cargo": "COORDINADOR LOGISTICO",
    "so": "Windows 10 Pro 64-bit",
    "hardware": "Core i5 / 8GB RAM / 256GB SSD",
    "marca": "PC de Mesa",
    "conectado_id": "sw-hp",
    "conectado": "Switch Core HP 24p",
    "enlace_tipo": "Cable UTP Cat 6",
    "puerto_switch": "Toma Pared Logística 1 -> Switch HP",
    "software": "ERP Logística, Despachos, WMS",
    "alerta": "Normal",
    "notas": "Puesto fijo de coordinación logística en Piso 2 operado por Juan José Toro."
  },
  {
    "id": "laptop-logistica",
    "nombre": "Portátil Logística",
    "piso": "Piso 2",
    "tipo": "Laptop / Portátil",
    "ip": "192.168.1.250",
    "mac": "F0:2F:74:90:02:02",
    "hostname": "AUXLOG",
    "usuario": "URAN GARCIA ANGEL DAVID",
    "cargo": "AUXILIAR DE GESTION LOGISTICA",
    "so": "Windows 11 Pro 64-bit",
    "hardware": "Core i5 / 16GB RAM / 512GB SSD",
    "marca": "Laptop Lenovo",
    "conectado_id": "sw-hp",
    "conectado": "Switch Core HP 24p",
    "enlace_tipo": "Cable UTP Cat 6",
    "puerto_switch": "Toma Pared Logística 2 -> Switch HP",
    "software": "ERP, Despachos, Guías de Transporte",
    "alerta": "Normal",
    "notas": "Portátil auxiliar de logística operado por Ángel David Urán."
  },
  {
    "id": "printer-stickers",
    "nombre": "Impresora de Stickers",
    "piso": "Piso 2",
    "tipo": "Periférico / Impresora",
    "ip": "192.168.1.169",
    "mac": "00:80:77:44:02:03",
    "hostname": "IMPRESORAL4260",
    "usuario": "COLABORADORES PISO 2",
    "cargo": "TALENTO HUMANO/ LOGISTICA/ PRODUCCION",
    "so": "Firmware Impresora",
    "hardware": "Epson EcoTank L4260",
    "marca": "Epson",
    "conectado_id": "isp-ruijie",
    "conectado": "Módem ISP 2 (Secundario)",
    "enlace_tipo": "Cable UTP Cat 6",
    "puerto_switch": "LAN Módem ISP 2",
    "software": "Drivers Térmicos / Etiquetas",
    "alerta": "Normal",
    "notas": "Impresora de stickers para empaque y despacho."
  },
  {
    "id": "printer-lavado",
    "nombre": "Impresora Etiquetas Lavado",
    "piso": "Piso 2",
    "tipo": "Periférico / Impresora",
    "ip": "192.168.1.49",
    "mac": "00:80:77:44:02:04",
    "hostname": "IMPRESORAINSLAV",
    "usuario": "TORO GARCIA JUAN JOSE",
    "cargo": "COORDINADOR LOGISTICO",
    "so": "Firmware Impresora Industrial",
    "hardware": "Impresora Térmica Ribbon para Satín/Nylon",
    "marca": "Industrial Textil",
    "conectado_id": "sw-hp",
    "conectado": "Switch Core HP 24p",
    "enlace_tipo": "Cable UTP Cat 6",
    "puerto_switch": "Puerto 15 Switch Core HP",
    "software": "Driver Etiquetas de Lavado Textil",
    "alerta": "Normal",
    "notas": "Impresora industrial de marquillas de instrucciones de lavado."
  },

  # PISO 3 (ADMINISTRACIÓN, GERENCIA, VENTAS, CONTABILIDAD, AVANSIS - 13 EQUIPOS)
  {
    "id": "sw-p3",
    "nombre": "Switch Principal Piso 3",
    "piso": "Piso 3",
    "tipo": "Switch",
    "ip": "192.168.1.3",
    "mac": "E0:CC:7A:44:55:66",
    "hostname": "SW-RACK-P3",
    "usuario": "Infraestructura Piso 3",
    "cargo": "SALA DE JUNTAS",
    "so": "Firmware Switch",
    "hardware": "Switch 16/24 Puertos Gigabit en Rack",
    "marca": "Tenda / Rack P3",
    "conectado_id": "sw-hp",
    "conectado": "Switch Core HP 24p",
    "enlace_tipo": "Cableado Vertical",
    "puerto_switch": "Troncal Vertical UTP Cat 6 desde Switch HP P2",
    "software": "Auto-sensing Gigabit",
    "alerta": "Normal",
    "notas": "Switch principal ubicado en rack de Piso 3 para toda el área administrativa."
  },
  {
    "id": "ap-gerencia",
    "nombre": "TP-Link Negro (Gerencia)",
    "piso": "Piso 3",
    "tipo": "Router / Gateway",
    "ip": "192.168.1.211",
    "mac": "30:B5:C2:77:88:99",
    "hostname": "ROUTER-GERENCIA-NEGRO",
    "usuario": "Luis Felipe Aristizábal",
    "cargo": "Router Exclusivo Gerente",
    "so": "TP-Link OS",
    "hardware": "Router Wi-Fi Dual Band Gigabit Negro",
    "marca": "TP-Link Negro",
    "conectado_id": "sw-p3",
    "conectado": "Switch Principal Piso 3",
    "enlace_tipo": "Cable UTP Cat 6",
    "puerto_switch": "Puerto 2 Switch Piso 3",
    "software": "SSID Privado Gerencia WPA3",
    "alerta": "Normal",
    "notas": "Router Wi-Fi exclusivo para el Gerente Luis Felipe Aristizábal."
  },
  {
    "id": "pc-gerente",
    "nombre": "Equipo Gerente (Luis Felipe)",
    "piso": "Piso 3",
    "tipo": "Puesto de Trabajo",
    "ip": "192.168.0.100",
    "mac": "84:A9:3E:12:03:01",
    "hostname": "PC-GERENCIA-GENERAL",
    "usuario": "Luis Felipe Aristizábal",
    "cargo": "Gerente General",
    "so": "Windows 11 Pro 64-bit",
    "hardware": "Core i7 / 16GB RAM / 1TB SSD",
    "marca": "PC Ejecutivo Gerencia",
    "conectado_id": "ap-gerencia",
    "conectado": "TP-Link Negro (Gerencia)",
    "enlace_tipo": "Cable UTP Cat 6",
    "puerto_switch": "LAN1 Router TP-Link Negro",
    "software": "Suite Ejecutiva, ERP, BI",
    "alerta": "Normal",
    "notas": "Equipo de gerencia general conectado por cable y Wi-Fi al TP-Link Negro."
  },
  {
    "id": "ap-juntas",
    "nombre": "TP-Link Blanco (Invitados Juntas)",
    "piso": "Piso 3",
    "tipo": "Wi-Fi / AP",
    "ip": "192.168.1.241",
    "mac": "30:B5:C2:11:22:33",
    "hostname": "AP-JUNTAS-BLANCO",
    "usuario": "Sala de Juntas / Visitas",
    "cargo": "Red Invitados Ocasional",
    "so": "TP-Link OS",
    "hardware": "Router Wi-Fi Blanco",
    "marca": "TP-Link Blanco",
    "conectado_id": "sw-p3",
    "conectado": "Switch Principal Piso 3",
    "enlace_tipo": "Cable UTP Cat 6",
    "puerto_switch": "Puerto 3 Switch Piso 3",
    "software": "Red de Invitados Aislada",
    "alerta": "Normal",
    "notas": "Punto de acceso para sala de juntas y visitantes ocasionales."
  },
  {
    "id": "printer-admin",
    "nombre": "Impresora Facturación",
    "piso": "Piso 3",
    "tipo": "Periférico / Impresora",
    "ip": "192.168.1.182",
    "mac": "00:1B:78:66:03:02",
    "hostname": "PRINTER-FACTURACION-P3",
    "usuario": "COLABORADORES TERCER PISO",
    "cargo": "GENERAL",
    "so": "Firmware Impresora Red",
    "hardware": "Impresora Láser de Red Multifuncional",
    "marca": "Láser Red",
    "conectado_id": "sw-p3",
    "conectado": "Switch Principal Piso 3",
    "enlace_tipo": "Cable UTP Cat 6",
    "puerto_switch": "Puerto 5 Switch Piso 3",
    "software": "Driver Facturación, Scanner Red",
    "alerta": "Normal",
    "notas": "Impresora de red para facturación y área administrativa."
  },
  {
    "id": "laptop-printer-adj",
    "nombre": "Portátil Junto a Impresora",
    "piso": "Piso 3",
    "tipo": "Laptop / Portátil",
    "ip": "192.168.1.153",
    "mac": "F0:2F:74:90:03:03",
    "hostname": "AUXCOM2",
    "usuario": "BERNAL VARGAS MARIA JOSÉ",
    "cargo": "APRENDIZ SENA ETAPA PRODUCTIVA",
    "so": "Windows 11 Pro 64-bit",
    "hardware": "Core i5 / 8GB RAM / 256GB SSD",
    "marca": "Laptop Lenovo",
    "conectado_id": "sw-p3",
    "conectado": "Switch Principal Piso 3",
    "enlace_tipo": "Cable UTP Cat 6",
    "puerto_switch": "Toma Pared junto a Impresora -> Switch P3",
    "software": "Office, ERP, Facturación",
    "alerta": "Normal",
    "notas": "Portátil ubicado al lado de la impresora operado por María José Bernal."
  },
  {
    "id": "laptop-ventas-angie",
    "nombre": "Portátil Angie (Ventas)",
    "piso": "Piso 3",
    "tipo": "Laptop / Portátil",
    "ip": "192.168.1.168",
    "mac": "54:EE:75:33:03:04",
    "hostname": "COODCOM",
    "usuario": "SALAMANCA VILLA ANGIE JULIETH",
    "cargo": "COORDINADORA JUNIOR COMERCIAL",
    "so": "Windows 11 Pro 64-bit",
    "hardware": "Core i5 / 16GB RAM / 512GB SSD",
    "marca": "Dell Inspiron",
    "conectado_id": "sw-p3",
    "conectado": "Switch Principal Piso 3",
    "enlace_tipo": "Cable UTP Cat 6",
    "puerto_switch": "Puesto Ventas 1 -> Switch P3",
    "software": "CRM, WhatsApp Web, Office",
    "alerta": "Normal",
    "notas": "Puesto comercial operado por Angie Julieth Salamanca."
  },
  {
    "id": "laptop-ventas-02",
    "nombre": "Portátil Ventas 02",
    "piso": "Piso 3",
    "tipo": "Laptop / Portátil",
    "ip": "192.168.1.185",
    "mac": "54:EE:75:33:03:05",
    "hostname": "AUXCOM1",
    "usuario": "OCAMPO CANDAMIL DIEGO ALEJANDRO",
    "cargo": "AUXILIAR COMERCIAL",
    "so": "Windows 11 Pro 64-bit",
    "hardware": "Core i5 / 8GB RAM / 256GB SSD",
    "marca": "HP Pavilion",
    "conectado_id": "sw-p3",
    "conectado": "Switch Principal Piso 3",
    "enlace_tipo": "Cable UTP Cat 6",
    "puerto_switch": "Puesto Ventas 2 -> Switch P3",
    "software": "CRM, Correo, ERP Comercial",
    "alerta": "Normal",
    "notas": "Puesto de ventas operado por Diego Alejandro Ocampo."
  },
  {
    "id": "laptop-ventas-03",
    "nombre": "AUXILIAR COMERCIAL 3",
    "piso": "Piso 3",
    "tipo": "Laptop / Portátil",
    "ip": "192.168.1.160",
    "mac": "54:EE:75:33:03:06",
    "hostname": "AUXCOM3",
    "usuario": "ARROYAVE PEREZ DEILY DAYHANA",
    "cargo": "ASESOR COMERCIAL",
    "so": "Windows 11 Pro",
    "hardware": "Core i5 / 8GB RAM / 256GB SSD",
    "marca": "Laptop HP",
    "conectado_id": "sw-p3",
    "conectado": "Switch Principal Piso 3",
    "enlace_tipo": "Cable UTP Cat 6",
    "puerto_switch": "Puesto Ventas 3 -> Switch P3",
    "software": "CRM, Correo, ERP Comercial",
    "alerta": "Normal",
    "notas": "Puesto de ventas operado por Deily Dayhana Arroyave."
  },
  {
    "id": "laptop-cristian-admin",
    "nombre": "Portátil Cristian (Analista Admin)",
    "piso": "Piso 3",
    "tipo": "Laptop / Portátil",
    "ip": "192.168.1.155",
    "mac": "54:EE:75:33:03:07",
    "hostname": "LIDERDO",
    "usuario": "GIRALDO HERRERA CRISTIAN FELIPE",
    "cargo": "LIDER DESARROLLO ORGANIZACIONAL",
    "so": "Windows 11 Pro 64-bit",
    "hardware": "Core i7 / 16GB RAM / 512GB SSD",
    "marca": "Asus ZenBook",
    "conectado_id": "sw-p3",
    "conectado": "Switch Principal Piso 3",
    "enlace_tipo": "Cable UTP Cat 6",
    "puerto_switch": "Puesto Admin -> Switch P3",
    "software": "Gestión Administrativa, BI, Procesos",
    "alerta": "Normal",
    "notas": "Portátil operado por Cristian Felipe Giraldo (Líder DO)."
  },
  {
    "id": "pc-juan-contab",
    "nombre": "PC Juan Esteban (Contabilidad)",
    "piso": "Piso 3",
    "tipo": "Puesto de Trabajo",
    "ip": "192.168.1.196",
    "mac": "B4:2E:99:40:03:08",
    "hostname": "COODCONT",
    "usuario": "CORRALES MARÍN JUAN ESTEBAN",
    "cargo": "COORDINADOR FINANCIERO",
    "so": "Windows 11 Pro 64-bit",
    "hardware": "Core i7 / 16GB RAM / 512GB SSD",
    "marca": "PC de Mesa",
    "conectado_id": "sw-p3",
    "conectado": "Switch Principal Piso 3",
    "enlace_tipo": "Cable UTP Cat 6",
    "puerto_switch": "Puesto Contabilidad 1 -> Switch P3",
    "software": "Avansis ERP Cliente, Portal Bancario, DIAN",
    "alerta": "Normal",
    "notas": "Puesto principal contable y financiero operado por Juan Esteban Corrales."
  },
  {
    "id": "pc-facturacion",
    "nombre": "PC Facturación",
    "piso": "Piso 3",
    "tipo": "Puesto de Trabajo",
    "ip": "192.168.1.221",
    "mac": "B4:2E:99:40:03:09",
    "hostname": "AUXCONT",
    "usuario": "TORRES MONTAÑO NICOLL XIOMARA",
    "cargo": "AUXILIAR DE TESORERIA",
    "so": "Windows 10 Pro 64-bit",
    "hardware": "Core i5 / 8GB RAM / 256GB SSD",
    "marca": "All-in-One HP",
    "conectado_id": "sw-p3",
    "conectado": "Switch Principal Piso 3",
    "enlace_tipo": "Cable UTP Cat 6",
    "puerto_switch": "Puesto Facturación -> Switch P3",
    "software": "Avansis Facturación, Impuestos, DIAN",
    "alerta": "Normal",
    "notas": "Puesto All-in-One de tesorería y facturación operado por Nicoll Xiomara Torres."
  },
  {
    "id": "pc-server",
    "nombre": "PC Servidor Principal (Avansis)",
    "piso": "Piso 3",
    "tipo": "Servidor",
    "ip": "192.168.1.227",
    "mac": "E4:54:E8:99:03:10",
    "hostname": "SERVTDOR",
    "usuario": "SALAZAR ARISTIZABAL ALEX MAURICIO",
    "cargo": "AUXILIAR CONTABLE",
    "so": "Windows Server / Windows 10 Pro",
    "hardware": "Core i7 / 32GB RAM / 1TB SSD RAID",
    "marca": "PC Torre Servidor",
    "conectado_id": "sw-p3",
    "conectado": "Switch Principal Piso 3",
    "enlace_tipo": "Cable UTP Cat 6",
    "puerto_switch": "Puerto 1 Switch Piso 3 (Prioridad)",
    "software": "Avansis ERP BD Engine, SQL Server Express, Compartidos",
    "alerta": "Crítico",
    "notas": "⚠️ PUNTO ÚNICO DE FALLO (SPOF CRÍTICO). Servidor principal del software ERP Avansis donde reside toda la contabilidad e inventario de la empresa. Ubicado físicamente en Contabilidad Piso 3."
  }
]
